coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

ignore:
  - "src/test/**/*"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/mocks/**"
  - "**/fixtures/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
  show_carryforward_flags: true

flags:
  gemini-feature:
    paths:
      - src/features/gemini
    carryforward: true
