version: '3.8'

services:
  gemini_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - DEFAULT_VOICE=Charon
      - DEFAULT_LANGUAGE=en-US
      - WS_PING_INTERVAL=30
      - WS_PING_TIMEOUT=10
      - RELOAD=true
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - gemini_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gemini_net:
    driver: bridge

volumes:
  logs:
