name: Test
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install -D vitest@latest jsdom@latest @testing-library/react@latest
          
      # Run lint first
      - name: Type check
        run: npm run typecheck || true
          
      # Run tests in CI mode
      - name: Run tests
        run: npm run test:ci
        env:
          CI: true
          NODE_ENV: test
            
      # Report results
      - name: Test Summary
        if: always()
        run: |
          echo "Test Results Summary:"
          echo "===================="
          echo "Environment: CI/Ubuntu-latest/Node ${{ matrix.node-version }}"
