name: Test
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      # Run lint first
      - name: Lint
        run: npm run lint
        continue-on-error: true
          
      # Run type checking
      - name: Type check
        run: npm run typecheck
        if: success() || failure() # Run even if lint fails
          
      # Run tests in CI mode
      - name: Run tests
        run: npm run test:ci
        env:
          CI: true
          NODE_ENV: test
          TEST_ENV: ci
          
      # Report test results
      - name: Upload test results
        if: success() || failure() # Upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage/
            test-results/
            
      # Add test summary
      - name: Test Summary
        run: |
          echo "Test Results Summary:"
          echo "===================="
          echo "Environment: CI/Ubuntu-latest/Node ${{ matrix.node-version }}"
          echo "Test command: npm run test:ci"
          
      # Notify on failure
      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Tests failed! Check the logs for details."
